# Adapted from https://github.com/hadley/testthat/blob/master/.travis.yml
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
cache: packages
r:
 - bioc-release
 - bioc-devel
env:
- R_QPDF=true

script: "sbt clean coverage test"

after_success: "sbt coveralls"
